insert into event (title, description, tags, email, owner_id, location) values ('Permanent Record', 'Drama', 'China', 'bsorensen0@bbb.org', 1, '9 Trailsway Pass');
insert into event (title, description, tags, email, owner_id, location) values ('Yankee Zulu', 'Comedy|Drama', 'Bangladesh', 'tbellini1@pagesperso-orange.fr', 1, '8691 Homewood Trail');
insert into event (title, description, tags, email, owner_id, location) values ('Jeepers Creepers 2', 'Horror|Thriller', 'France', 'eostick2@rediff.com', 1, '8865 Mosinee Trail');
insert into event (title, description, tags, email, owner_id, location) values ('For All Mankind', 'Documentary', 'United States', 'hwysome3@google.cn', 1, '90426 Quincy Place');
insert into event (title, description, tags, email, owner_id, location) values ('Best Years of Our Lives, The', 'Drama|War', 'Portugal', 'bpherps4@skype.com', 1, '7 Lyons Street');
insert into event (title, description, tags, email, owner_id, location) values ('Behind Enemy Lines II: Axis of Evil', 'Action|Thriller|War', 'Tunisia', 'sbeatey5@homestead.com', 1, '6 Ridgeview Point');
insert into event (title, description, tags, email, owner_id, location) values ('Coneheads', 'Comedy|Sci-Fi', 'Ireland', 'mgenty6@engadget.com', 1, '43 Arrowood Place');
insert into event (title, description, tags, email, owner_id, location) values ('Pretty in Pink', 'Comedy|Drama|Romance', 'Sweden', 'jnorthcote7@lulu.com', 1, '05287 Vernon Terrace');
insert into event (title, description, tags, email, owner_id, location) values ('Best of Times, The', 'Comedy|Drama', 'Czech Republic', 'hgellert8@nps.gov', 1, '3 Mosinee Drive');
insert into event (title, description, tags, email, owner_id, location) values ('Baraka', 'Documentary', 'Sweden', 'tgasken9@theglobeandmail.com', 1, '49290 Shelley Center');
insert into event (title, description, tags, email, owner_id, location) values ('Facing Windows (Finestra di fronte, La)', 'Drama|Romance', 'Canada', 'mprendivillea@nytimes.com', 1, '7 Eastlawn Pass');
insert into event (title, description, tags, email, owner_id, location) values ('Jamie Marks Is Dead', 'Drama|Thriller', 'United Kingdom', 'mmanvellb@theglobeandmail.com', 1, '97 Bayside Lane');
insert into event (title, description, tags, email, owner_id, location) values ('Crime at the Chinese Restaurant', 'Comedy|Mystery|Thriller', 'Germany', 'shartlandc@sohu.com', 1, '34012 Jenifer Hill');
insert into event (title, description, tags, email, owner_id, location) values ('Idiot, The (Hakuchi)', 'Crime|Drama|Romance', 'Thailand', 'rphippind@about.com', 1, '39 Blaine Plaza');
insert into event (title, description, tags, email, owner_id, location) values ('10 Questions for the Dalai Lama', 'Documentary', 'Russia', 'pkeyzore@oracle.com', 1, '985 Waywood Trail');
insert into event (title, description, tags, email, owner_id, location) values ('Dacii', 'Drama|War', 'Honduras', 'jparrf@com.com', 1, '166 Kropf Court');
insert into event (title, description, tags, email, owner_id, location) values ('Death Sentence', 'Drama|Thriller', 'Kyrgyzstan', 'svareyg@php.net', 1, '4033 Jay Parkway');
insert into event (title, description, tags, email, owner_id, location) values ('What If', 'Comedy|Drama|Romance', 'Vietnam', 'ashakeladyh@surveymonkey.com', 1, '7 Golden Leaf Point');
insert into event (title, description, tags, email, owner_id, location) values ('Into the West', 'Adventure|Drama|Western', 'Greece', 'gswantoni@reuters.com', 1, '06412 Melody Center');
insert into event (title, description, tags, email, owner_id, location) values ('Ice Soldiers', 'Action|Sci-Fi', 'Russia', 'llundbergj@oakley.com', 1, '56964 Di Loreto Parkway');
insert into event (title, description, tags, email, owner_id, location) values ('Hostage', 'Action|Crime|Drama|Thriller', 'Micronesia', 'bfellgatek@telegraph.co.uk', 1, '856 Coleman Way');
insert into event (title, description, tags, email, owner_id, location) values ('American Tail: Fievel Goes West, An', 'Adventure|Animation|Children|Musical|Western', 'China', 'dstanesbyl@drupal.org', 1, '56019 Hazelcrest Hill');
insert into event (title, description, tags, email, owner_id, location) values ('Cantante, El', 'Drama|Musical', 'Indonesia', 'estuckfordm@time.com', 1, '5683 Bellgrove Road');
insert into event (title, description, tags, email, owner_id, location) values ('Behind Blue Skies (Himlen är oskyldigt blå)', 'Drama', 'Norway', 'mgorrien@t.co', 1, '51315 Glacier Hill Court');
insert into event (title, description, tags, email, owner_id, location) values ('Frenzy', 'Thriller', 'Ukraine', 'gjostano@netvibes.com', 1, '27 Waywood Road');
